trainservice:
  SupportDetails:
    Personal:
      name: "Train Service - Default"
    ContactDetails:
      email: trainservice@cupofjavatech.com
      phone:
        - 1 (800) 111-111
        - 1 (800) 111-222